module.exports = {
    "id": "snake_game",
    "name": "Snake Game",
    "primary": "program",
    "secondary": true,
    "imageCount": 3,
    "designText": "<p>An implementation of the classic Snake game in HTML5, created for the Fall 2016 class of CIS 580 at Kansas State University.</p> <h1>Design Requirements</h1> <p>The game is implemented in JavaScript using the HTML5 canvas element using the provided game framework.</p> <ul> <li>The snake consists of a head and multiple body segments which always follow behind it and are rendered on-screen. The segments should not be fixed in position, i.e. the tail should move around the screen. The head and body segments can be composed of rectangles, arcs, or images.</li> <li>Colliding the snake's head with a body segment loses the game.</li> <li>Periodically, an apple (image or arc) appears on-screen. If the snake's head collides with it, the user gains points in their score.</li> <li>Periodically, the snake grows an extra segment. This can either be timed, or triggered by eating an apple, or similar mechanism. The segment should appear at the end of the snake and behave like the existing segments.</li> </ul> <h1>Style Choices</h1> <ul> <li>The choice to work with basic Javascript to create the artwork was made to familiarize myself with the concept in Javascript.</li> <li>The goal was to create a game that was simplistic and the choice was made to limit all the shapes in the game to circles of the same size.</li> </ul> <a href=/external/snake><div id='play-button'> Play the Game! </div></a><a href='https://github.com/CjoewD/JavaScript-Snake-Game' target='_blank'><div id='play-button'> View GitHub Repo </div></a>",
    "codingText": "<p>An implementation of the classic Snake game in HTML5, created for the Fall 2016 class of CIS 580 at Kansas State University.</p> <h1>Requirements</h1> <p>The game is implemented in JavaScript using the HTML5 canvas element using the provided game framework.</p> <ul> <li>The snake consists of a head and multiple body segments which always follow behind it and are rendered on-screen. The segments should not be fixed in position, i.e. the tail should move around the screen. The head and body segments can be composed of rectangles, arcs, or images.</li> <li>The snake's head can move left, right, up, and down. Optionally you may prevent the snake from turning back upon its own body.</li> <li>Moving the snake's head off-screen (out of the rectangle between 0, 0, and the canvas width and height) loses the game.</li> <li>Colliding the snake's head with a body segment loses the game.</li> <li>When the game is lost, a message to that effect should be displayed to the players. This can be done with the canvas' drawText method or an HTML element overlaying the canvas. It should not be done with the alert() function.</li> <li>When the game is lost, the snake should no longer move.</li> <li>Periodically, an apple (image or arc) appears on-screen. If the snake's head collides with it, the user gains points in their score.</li> <li>The player's current score appears on-screen (this can be done with the canvas's draw-text method, or with an html element overlaying the canvas).</li> <li>Periodically, the snake grows an extra segment. This can either be timed, or triggered by eating an apple, or similar mechanism. The segment should appear at the end of the snake and behave like the existing segments.</li> <li>Instructions for playing the made should be made available to the player. At a minimum, these should be incorporated into the webpage below the canvas, though they could also be displayed within the canvas using the drawText method or an HTML element overlaying the canvas. If either of the latter is done, the game should pause while they are displayed.</li> </ul> <h1>Optional Requirements</h1> <ul> <li>You may optionally implement obstacles within the game's area. Should the snake collide with one, the game should end.</li> </ul> <a href=/external/snake id='button-showcase-content'><div id='play-button'> Play the Game! </div></a> <a href='https://github.com/CjoewD/JavaScript-Snake-Game' target='_blank' id='button-showcase-content'><div id='play-button'> View GitHub Repo </div></a>"
}
