module.exports = {
    "id": "tied_&_true",
    "name": "Tied & True",
    "primary": "design",
    "secondary": true,
    "imageCount": 5,
    "designText": "<p>Collaborative senior capstone project with an apparel design and marketing group, created for the Spring 2018 class of ART 580 Graphic Design Senior Studio at Kansas State University.</p> <h1>Design Requirements</h1> <ul> <li>Wordmark and logomark.</li> <li>Corporate colors.</li> <li>Corporate typefaces.</li> <li>Standard typographic treatments.</li> <li>Standard image treatments.</li> <li>External building signage.</li> <li>In-store elements (such as bathroom signs and clothing tags).</li> <li>Other brand applications (such as water bottle and canvas bag).</li> </ul> <h1>Meetings</h1> <ul> <li>Each graphic design student would meet with their group of 2-3 apparel design students on a regular basis to go over expectations and progress.</li> <li>We were to have our design match the personality of the store, and the needs/wants of the clients. Yet we were to push for what we thought the better choice was.</li> <li>The store name and location were given to me.</li> </ul> <h1>Logo</h1> <ul> <li>From my clients, the logo was to be a pale green and brown.</li> <li>The store itself was industrial, brick and cement, hanging Edison bulb lights, etc.. Check out the mood board on the github repo!</li> <li>Influenced by the moodboard, I wanted it urban and industrial looking. Bahn Pro Regular was the font used.</li> </ul> <h1>Corporate Fonts</h1> <ul> <li>Babas Neue was selected as the primary title, pullout, and general emphasis font. It mimicked a lot of the structure from the logo's font but in a subtle way. </li> <li>Arvo was selected as the body font because it scales well, and a slab serif was desired for the masculine look.</li> </ul> <h1>Image Treatments</h1> <ul> <li>The clothing should be the main focus. Therefore, only the logo should be overtop of the models (optional) and very minimal other type and elements.</li> <li>Occasionally a rectangle could be placed behind the models to pop them forward. Mimicking the logo while giving the image a higher price tag look.</li> </ul> <h1>Website</h1> <ul> <li>The clients expressed that clothing would not be sold on the website. That their would be a blog, promotions, and Instagram feed with customers wearing Tied & True clothing.</li> <li>Bringing in the industrial appearance, I added the light brick repeating pattern in the header.</li> <li>A promotions bar was added under that for catching the users eye and easily viewable from any page.</li> </ul> <br><p>***Credits on github repo***</p><a href='http://external.CjoewD.com/public/tied&true' target='_blank'><div id='play-button'> See the Website! </div></a><a href='https://github.com/CjoewD/HTML-Tied-True' target='_blank'><div id='play-button'> View GitHub Repo </div></a>",
    "codingText": "<p>Collaborative senior capstone project with an apparel design and marketing group, created for the Spring 2018 class of ART 580 Graphic Design Senior Studio at Kansas State University.</p> <h1>Website Design</h1> <ul> <li>The clients expressed that clothing would not be sold on the website. That there would be a blog, promotions, and Instagram feed with customers wearing Tied & True clothing.</li> <li>Bringing in the industrial appearance, I added the light brick repeating pattern in the header.</li> <li>A promotions bar was added under that for catching the users eye and easily viewable from any page.</li> </ul> <h1>Website Programming</h1> <ul> <li>Only basic html, css and JavaScript was used.</li> <li>JavaScript was used for rotating the Instagram feed on the homepage (images and information from file), moving the fixed content box on the blog page, and the mobile hamburger menu.</li> </ul> <br> <p>***Credits on github repo***</p> <a href='http://external.CjoewD.com/public/tied&true' target='_blank'><div id='play-button'> See the Website! </div></a> <a href='https://github.com/CjoewD/HTML-Tied-True' target='_blank'><div id='play-button'> View GitHub Repo </div></a> "
}
