module.exports = {
    "id": "asteroid_game",
    "name": "Asteroid Game",
    "primary": "program",
    "secondary": true,
    "imageCount": 2,
    "designText": "<p>A clone of the arcade classic Asteroids in HTML5, created for the Fall 2016 class of CIS 580 at Kansas State University.</p> <h1>Design Requirements</h1> <ul> <li>Your game should involve steering a player's ship around space.</li> <li>You should render a significant number (at least ten) asteroids on screen. </li> <li>Asteroids should move along an initially random velocity vector. If they move off-screen, they should wrap to the opposite side of the screen.</li> <li>The player may shoot lasers, which travel across the screen and disappear when they cross the edge. </li> <li>A laser will break an asteroid into two or more smaller pieces when it hits them. These pieces have part of the original asteroid's mass, and velocities that move away from each other. If an asteroid is small enough, it is simply destroyed.</li> </ul> <h1>Style Choices</h1> <ul> <li>Overall style of the game was chosen to be simple with just outlines of the objects.</li> <li>Asteroids change color, red color, when they are small enough to destroyed when hit.</li> </ul> <br><p>***Credits on github repo***</p><a href=/external/asteroid><div id='play-button'> Play the Game! </div></a><a href='https://github.com/CjoewD/JavaScript-Asteroids-Game' target='_blank'><div id='play-button'> View GitHub Repo </div></a>",
    "codingText": "<p>A clone of the arcade classic Asteroids in HTML5, created for the Fall 2016 class of CIS 580 at Kansas State University.</p> <h1>Requirements</h1> <p>You will be building a clone of Asteroids, where the purpose is to pilot a ship through an astroid field without dying.<p> <ul> <li>Your game should involve steering a player's ship around space. Should you move off-screen, your player should wrap back on-screen on the opposite side.</li> <li>You should render a significant number (at least ten) asteroids on screen. If all asteroids are destroyed, a new level with more asteroids is begun.</li> <li>Asteroids should move along an initially random velocity vector. If they move off-screen, they should wrap to the opposite side of the screen.</li> <li>Asteroids that collide with one another should break away from each other according to Newtonian mechanics while playing a sound effect. Asteroids should be of different masses, determined randomly when created.</li> <li>Asteroids destroy the player's ship when collided with, playing a sound effect. The player begins with three lives, which are displayed in a GUI.</li> <li>The player may shoot lasers, which travel across the screen and disappear when they cross the edge. They also play a sound effect when fired.</li> <li>A laser will break an asteroid into two or more smaller pieces when it hits them. These pieces have part of the original asteroid's mass, and velocities that move away from each other. If an asteroid is small enough, it is simply destroyed.</li> <li>The player's score, level, and lives are displayed on the game screen in some fashion - either through the drawText() method or via an HTML element overlayed on the game screen. Instructions on how to play the game appear in some easily-accessible fashion, i.e. on the page, or over the game screen accessed with the esc key.</li> </ul> <h1>Optional Requirements</h1> <ul> <li>The ship can warp to a random location on screen when a button is pressed.</li> <li>UFOs appear periodically and shoot at the player. These can be destroyed with lasers.</li> </ul> <br><p>***Credits on github repo***</p><a href=/external/asteroid><div id='play-button'> Play the Game! </div></a> <a href='https://github.com/CjoewD/JavaScript-Asteroids-Game' target='_blank'><div id='play-button'> View GitHub Repo </div></a>"
}
