module.exports = {
    "id": "pipes_game",
    "name": "Pipes Game",
    "primary": "program",
    "secondary": true,
    "imageCount": 4,
    "designText": "<p>A simple plumbing game template in HTML5, created for the Fall 2016 class of CIS 580 at Kansas State University.</p> <h1>Design Requirements</h1> <ul> <li>The game world is divided into a regular grid, in which tiles representing pipes can be placed.</li> <li>At the start of each level, an un-editable starting pipe and ending pipe appear.</li> <li>At the start of the level, 'fluid' begins to flow from the start pipe. If the fluid manages to reach the end of assembled pipes, the game is lost.</li> </ul> <h1>Style Choices</h1> <ul> <li>Most of the pipes were provided by open source location. Thin straight piece, large cross section, and starting/ending pipes modified by me.</li> <li>Dirt tiles were from open source locations.</li> <li>The user interface and water is made from Javascript code.</li> <li>The instruction page was made using Photoshop.</li> </ul> <br><p>***Credits on github repo***</p><a href=/external/pipes><div id='play-button'> Play the Game! </div></a><a href='https://github.com/CjoewD/JavaScript-Pipes-Game' target='_blank'><div id='play-button'> View GitHub Repo </div></a>",
    "codingText": "<p>A simple plumbing game template in HTML5, created for the Fall 2016 class of CIS 580 at Kansas State University.</p> <h1>Requirements</h1> <p>For this assignment, you will be creating a clone of Pipe Mania, which will need to meet the following requirements:</p> <ul> <li>The game world is divided into a regular grid, in which tiles representing pipes can be placed.</li> <li>At the start of each level, an un-editable starting pipe and ending pipe appear. If the player manages to connect these with pipes, the level is completed. The start and end connection of the pipes should be available.</li> <li>At the start of the level, 'fluid' begins to flow from the start pipe. If the fluid manages to reach the end of assembled pipes, the game is lost.</li> <li>The game score and level are represented on-screen.</li> <li>The kind of pipe available appear in random order, and the player can place them by left-clicking on the board.</li> <li>Right-clicking on a pipe that does not yet have fluid in it rotates the pipe tile. Pipes with fluid in them cannot be rotated.</li> <li>The speed at which fluid fills pipes increases as the player advances in level.</li> <li>Placing pipes, rotating pipes, finishing a level, and loosing the game should all have sound effects that play when these events happen.</li> <li>The game should play background music.</li> <li>Instructions for playing the game should appear in-game or on the page.</li> </ul> <h1>Optional Requirements</h1> <ul> <li>Add at least 3 additional kinds of pipes with special attributes (i.e. a reservoir that fills up more slowly).</li></ul> <br><p>***Credits on github repo***</p><a href=/external/pipes><div id='play-button'> Play the Game! </div></a><a href='https://github.com/CjoewD/JavaScript-Pipes-Game' target='_blank'><div id='play-button'> View GitHub Repo </div></a>"
}
